name: "main deploy integración github - s3"

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  tests:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with: 
          aws-region: ${{ secrets.S3_BUCKET_REGION }}
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT }}:role/role-fantasysportclub
          role-session-name: GithubSession
      
      - run: aws sts get-caller-identity

      - run: aws s3 sync ./index.html s3://${{ secrets.S3_BUCKET }} --delete


        